//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResistorCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResistorCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.00
        ///1.01
        ///1.02
        ///1.04
        ///1.05
        ///1.06
        ///1.07
        ///1.09
        ///1.10
        ///1.11
        ///1.13
        ///1.14
        ///1.15
        ///1.17
        ///1.18
        ///1.20
        ///1.21
        ///1.23
        ///1.24
        ///1.26
        ///1.27
        ///1.29
        ///1.30
        ///1.32
        ///1.33
        ///1.35
        ///1.37
        ///1.38
        ///1.40
        ///1.42
        ///1.43
        ///1.45
        ///1.47
        ///1.49
        ///1.50
        ///1.52
        ///1.54
        ///1.56
        ///1.58
        ///1.60
        ///1.62
        ///1.64
        ///1.65
        ///1.67
        ///1.69
        ///1.72
        ///1.74
        ///1.76
        ///1.78
        ///1.80
        ///1.82
        ///1.84
        ///1.87
        ///1.89
        ///1.91
        ///1.93
        ///1.96
        ///1.98
        ///2.00
        ///2.03
        ///2.05
        ///2.08
        ///2.10
        ///2.13
        ///2.15
        ///2.18
        ///2.21
        ///2.23
        ///2.26
        ///2.29
        ///2.32
        ///2.34
        ///2.37
        ///2.40
        ///2.43
        ///2.46
        ///2.49
        ///2.52
        ///2.55
        ///2.58
        ///2.61
        ///2.64
        ///2.67
        ///2.71
        ///2.74
        ///2.77
        ///2.80
        ///2.84
        ///2.87
        ///2.91
        ///2.94
        ///2.98
        ///3.01
        ///3.05
        ///3.09
        ///3.1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string serieE192_sorted {
            get {
                return ResourceManager.GetString("serieE192_sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.00
        ///1.10
        ///1.20
        ///1.30
        ///1.50
        ///1.60
        ///1.80
        ///2.00
        ///2.20
        ///2.40
        ///2.70
        ///3.00
        ///3.30
        ///3.60
        ///3.90
        ///4.30
        ///4.70
        ///
        ///5.10
        ///5.60
        ///6.20
        ///6.80
        ///7.50
        ///8.20
        ///9.10.
        /// </summary>
        internal static string serieE24_sorted {
            get {
                return ResourceManager.GetString("serieE24_sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.00
        ///1.05
        ///1.10
        ///1.15
        ///1.21
        ///1.27
        ///1.33
        ///1.40
        ///1.47
        ///1.54
        ///1.62
        ///1.69
        ///1.78
        ///1.87
        ///1.96
        ///2.05
        ///2.15
        ///2.26
        ///2.37
        ///2.49
        ///2.61
        ///2.74
        ///2.87
        ///3.01
        ///3.16
        ///3.32
        ///3.48
        ///3.65
        ///3.83
        ///4.02
        ///4.22
        ///4.42
        ///4.64
        ///4.87
        ///5.11
        ///5.36
        ///5.62
        ///5.90
        ///6.19
        ///6.49
        ///6.81
        ///7.15
        ///7.50
        ///7.87
        ///8.25
        ///8.66
        ///9.09
        ///9.53.
        /// </summary>
        internal static string serieE48_sorted {
            get {
                return ResourceManager.GetString("serieE48_sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.00
        ///1.02
        ///1.05
        ///1.07
        ///1.10
        ///1.13
        ///1.15
        ///1.18
        ///1.21
        ///1.24
        ///1.27
        ///1.30
        ///1.33
        ///1.37
        ///1.40
        ///1.43
        ///1.47
        ///1.50
        ///1.54
        ///1.58
        ///1.62
        ///1.65
        ///1.69
        ///1.74
        ///1.78
        ///1.82
        ///1.87
        ///1.91
        ///1.96
        ///2.00
        ///2.05
        ///2.10
        ///2.15
        ///2.21
        ///2.26
        ///2.32
        ///2.37
        ///2.43
        ///2.49
        ///2.55
        ///2.61
        ///2.67
        ///2.74
        ///2.80
        ///2.87
        ///2.94
        ///3.01
        ///3.09
        ///3.16
        ///3.24
        ///3.32
        ///3.40
        ///3.48
        ///3.57
        ///3.65
        ///3.74
        ///3.83
        ///3.92
        ///4.02
        ///4.12
        ///4.22
        ///4.32
        ///4.42
        ///4.53
        ///4.64
        ///4.75
        ///4.87
        ///4.99
        ///5.11
        ///5.23
        ///5.36
        ///5.49
        ///5.62
        ///5.76
        ///5.90
        ///6.04
        ///6.19
        ///6.34
        ///6.49
        ///6.65
        ///6.81
        ///6.98
        ///7.15
        ///7.32
        ///7.50
        ///7.68
        ///7.87
        ///8.06
        ///8.25
        ///8.45
        ///8.66
        ///8.87
        ///9.09
        ///9.31
        ///9.53
        ///9.76.
        /// </summary>
        internal static string serieE96_sorted {
            get {
                return ResourceManager.GetString("serieE96_sorted", resourceCulture);
            }
        }
    }
}
