#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CSE.Resource", IsApplication=true)]

namespace CSE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int BtnOk = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int ibtnPlayerChat = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ibtnPlayerElephant = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int ibtnPlayerSouris = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int txtChoiceComputer = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int txtChoicePlayer = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int txtResult = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int txvScoreComputer = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int txvScorePlayer = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ResultView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int chat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int elephant = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int souris = 2130837506;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
